//! @file vdc_io.cpp
//! @brief Implementation of mesh output functions for DelaunayIsosurface.

#include "vdc_io.h"
#include <fstream>
#include <iomanip>

// ============================================================================
// OFF Format Output
// ============================================================================

void write_off_delaunay(const std::string &filename, const DelaunayIsosurface &iso_surface) {
    std::ofstream out(filename);
    if (!out.is_open()) {
        std::cerr << "Error: Could not open file " << filename << " for writing." << std::endl;
        return;
    }

    // OFF header
    out << "OFF\n";

    // Number of vertices, faces, edges (edges typically 0 for mesh files)
    size_t num_vertices = iso_surface.isovertices.size();
    size_t num_faces = iso_surface.triangles.size();
    out << num_vertices << " " << num_faces << " 0\n";

    // Write vertices with high precision
    out << std::fixed << std::setprecision(8);
    for (const auto& v : iso_surface.isovertices) {
        out << v.x() << " " << v.y() << " " << v.z() << "\n";
    }

    // Write faces (triangles)
    for (const auto& tri : iso_surface.triangles) {
        out << "3 " << tri[0] << " " << tri[1] << " " << tri[2] << "\n";
    }

    out.close();

    std::cout << "Wrote " << num_vertices << " vertices and "
              << num_faces << " triangles to " << filename << std::endl;
}

// ============================================================================
// PLY Format Output
// ============================================================================

void write_ply_delaunay(const std::string &filename, const DelaunayIsosurface &iso_surface) {
    std::ofstream out(filename);
    if (!out.is_open()) {
        std::cerr << "Error: Could not open file " << filename << " for writing." << std::endl;
        return;
    }

    size_t num_vertices = iso_surface.isovertices.size();
    size_t num_faces = iso_surface.triangles.size();

    // PLY header
    out << "ply\n";
    out << "format ascii 1.0\n";
    out << "comment Generated by vdc-del (Delaunay-based dual contouring)\n";
    out << "element vertex " << num_vertices << "\n";
    out << "property float x\n";
    out << "property float y\n";
    out << "property float z\n";
    out << "element face " << num_faces << "\n";
    out << "property list uchar int vertex_indices\n";
    out << "end_header\n";

    // Write vertices with high precision
    out << std::fixed << std::setprecision(8);
    for (const auto& v : iso_surface.isovertices) {
        out << v.x() << " " << v.y() << " " << v.z() << "\n";
    }

    // Write faces (triangles)
    for (const auto& tri : iso_surface.triangles) {
        out << "3 " << tri[0] << " " << tri[1] << " " << tri[2] << "\n";
    }

    out.close();

    std::cout << "Wrote " << num_vertices << " vertices and "
              << num_faces << " triangles to " << filename << std::endl;
}
